database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: ${DWDEMO_USER}

  # the password
  password: ${DWDEMO_PASSWORD}

  # the JDBC URL
  url: jdbc:postgresql://localhost/dropwizard-started

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyApplication Health Check */ SELECT 1"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

#logging:
#  level: INFO
#  loggers:
#    "io.dropwizard": INFO
#    "org.hibernate.SQL":
#      level: DEBUG
#      additive: false
#      appenders:
#        - type: file
#          currentLogFilename: /var/log/dropwizard/myapplication-sql.log
#          archivedLogFilenamePattern: /var/log/dropwizard/myapplication-sql-%d.log.gz
#          archivedFileCount: 5
#  appenders:
#    - type: console